final products = [
  {
    'id': 1,
    'title': 'Nike Air Max 270',
    'imageURL':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWPJFbPY24_QMEBZwHwjORfHDppEkF9g-Bt8XcV0pLCRnHCXmhY1UULmqabVgH3Cjpgog&usqp=CAU',
    'price': 150,
    'old_price': 200,
    'is_favorite': false,
    'rating': 4.5,
    'reviews': 120,
    'category': 'Running',
    'sizes': [7, 8, 9, 10, 11],
    'colors': [0xFF000000, 0xFFFFFFFF, 0xFFFF0000],
  },
  {
    'id': 2,
    'title': 'Adidas Ultraboost',
    'imageURL':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWPJFbPY24_QMEBZwHwjORfHDppEkF9g-Bt8XcV0pLCRnHCXmhY1UULmqabVgH3Cjpgog&usqp=CAU',
    'price': 180,
    'old_price': 220,
    'is_favorite': true,
    'rating': 4.7,
    'reviews': 95,
    'category': 'Running',
    'sizes': [7, 8, 9, 10, 11],
    'colors': [0xFF000000, 0xFFFFFFFF, 0xFFFF0000],
  },
  {
    'id': 3,
    'title': 'Puma RS-X',
    'imageURL': 'https://i.ebayimg.com/images/g/51IAAeSwTyFop8Fy/s-l400.jpg',
    'price': 130,
    'old_price': 170,
    'is_favorite': false,
    'rating': 4.3,
    'reviews': 80,
    'category': 'Casual',
    'sizes': [7, 8, 9, 10, 11],
    'colors': [0xFF000000, 0xFFFFFFFF, 0xFFFF0000],
  },
  {
    'id': 4,
    'title': 'Reebok Classic',
    'imageURL':
        'https://brand.assets.adidas.com/image/upload/f_auto,q_auto:best,fl_lossy/PAC_ORIGINALS_SHOES_PLP_IWP_TILE_CAMPUS_5e49714426.jpg',
    'price': 120,
    'old_price': 160,
    'is_favorite': true,
    'rating': 4.6,
    'reviews': 110,
    'category': 'Casual',
    'sizes': [7, 8, 9, 10, 11],
    'colors': [0xFF000000, 0xFFFFFFFF, 0xFFFF0000],
  },
];
